### ISSUE TITLE
Extend section of pixels for no-hair-flip, or add new option?

### ISSUE THREAD

**Issue by AnUnVi** [FM1337/injector_bug_reports#1]
Hi!
Hopefully this doesn't come across as obnoxious - I know when it comes to popular programs made for free, it's easy to get inundated with requests and demands.
First off, let me just say that I absolutely love the Injector, and how simple and effective it is when adding new sprites. It really is a fantastic way to personalize your experience!
However, I tried injecting a set of sprites and kept running into a particular issue - it's an asymmetrical sprite that has hair covering half the face, and as a result it isn't covered by the non-flip hair option. I've found that just flipping the hair really doesn't work. I also tried it on Falkner's sprites as a test, and ran into the same issue. 
I think that this issue could be resolved by either extending the pre-existing area that doesn't get flipped, or adding it as a new option in case that creates more problems?
It would need to be changed from roughly 8 pixels to 11 pixels.
Attached are the sprites I've been trying to add.
Thank you for your consideration!

![amphina template](https://user-images.githubusercontent.com/36710811/102145458-7f467200-3e24-11eb-9f3a-35449a83e976.png)

**Comment by FM1337** [comment]
Not really much I can do about that, I didn't write the injector itself, I wrote the website and backend code that interfaces with the injector application. You'll need to speak to Shockslayer about this, sorry :(
